name: Android APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install node dependencies
        run: |
          npm ci

      - name: Make gradlew executable
        run: |
          chmod +x android/gradlew

      - name: Build release APK
        run: |
          cd android
          # Build release (unsigned) APK; runner is Ubuntu so Windows colon-path bug is avoided.
          ./gradlew assembleRelease --no-daemon --stacktrace

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: |
            android/app/build/outputs/**/*.apk
            android/app/build/outputs/**/*.aab
